package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"

	"path/filepath"
	"strings"

	"github.com/charmbracelet/lipgloss"
	"github.com/spf13/cobra"
)

var (
	installSuccessStyle = lipgloss.NewStyle().Foreground(lipgloss.Color("42"))
	installWarnStyle    = lipgloss.NewStyle().Foreground(lipgloss.Color("208"))
	installInfoStyle    = lipgloss.NewStyle().Foreground(lipgloss.Color("86"))
	installErrorStyle   = lipgloss.NewStyle().Foreground(lipgloss.Color("196"))
)

func writeLocalMergedGlobal(src string, dryRun bool) {
	if dryRun {
		return
	}
	userSrc := filepath.Join(filepath.Dir(src), "USER_AGENTS.md")
	rawBytes, err := os.ReadFile(src)
	if err != nil {
		return
	}
	raw := string(rawBytes)
	body := mergeUserAgents(raw, userSrc)
	out := filepath.Join(repoRoot(), "GLOBAL_AGENTS.local.md")
	banner := "<!-- Generated by `just install`. Merged USER_AGENTS.md; gitignored. Use @GLOBAL_AGENTS.local.md in Cursor for combined context. -->\n\n"
	os.WriteFile(out, []byte(banner+body), 0644)
	fmt.Println(installSuccessStyle.Render(fmt.Sprintf("Wrote: %s", out)))
}

func doLinkOrCopy(src, dest string, useCopy, dryRun bool) {
	if dryRun {
		verb := "symlink"
		if useCopy {
			verb = "cp"
		}
		fmt.Println(installInfoStyle.Render(fmt.Sprintf("[dry-run] %s %s -> %s", verb, src, dest)))
		return
	}
	os.MkdirAll(filepath.Dir(dest), 0755)
	os.Remove(dest)
	if useCopy {
		b, _ := os.ReadFile(src)
		os.WriteFile(dest, b, 0644)
		fmt.Println(installSuccessStyle.Render(fmt.Sprintf("Copied: %s", dest)))
	} else {
		absSrc, _ := filepath.Abs(src)
		os.Symlink(absSrc, dest)
		fmt.Println(installSuccessStyle.Render(fmt.Sprintf("Symlinked: %s -> %s", dest, absSrc)))
	}
}

func deployGlobalAgentsMarkdown(src, dest string, withHooks, useCopy, dryRun bool) {
	if dryRun {
		fmt.Println(installInfoStyle.Render(fmt.Sprintf("[dry-run] write %s (with_hooks=%v, copy fallback=%v)", dest, withHooks, useCopy)))
		return
	}
	rawBytes, err := os.ReadFile(src)
	if err != nil {
		return
	}
	raw := string(rawBytes)
	userSrc := filepath.Join(filepath.Dir(src), "USER_AGENTS.md")
	body := mergeUserAgents(raw, userSrc)
	hasUserContent := body != raw

	if withHooks {
		body = stripHookableSections(body)
	} else {
		body = stripHookableDelimiterLines(body)
		if body == raw && !hasUserContent {
			doLinkOrCopy(src, dest, useCopy, false)
			return
		}
	}
	os.MkdirAll(filepath.Dir(dest), 0755)
	os.Remove(dest)
	os.WriteFile(dest, []byte(body), 0644)
	fmt.Println(installSuccessStyle.Render(fmt.Sprintf("Wrote: %s", dest)))
}

func writeCursorMdc(globalPath string, stripHooks, dryRun bool) {
	dest := filepath.Join(getHomeDir(), ".cursor/rules/global-agents.mdc")
	if dryRun {
		fmt.Println(installInfoStyle.Render(fmt.Sprintf("[dry-run] write %s (frontmatter + GLOBAL_AGENTS.md, strip_hooks=%v)", dest, stripHooks)))
		return
	}
	os.MkdirAll(filepath.Dir(dest), 0755)
	rawBytes, _ := os.ReadFile(globalPath)
	raw := string(rawBytes)

	userSrc := filepath.Join(filepath.Dir(globalPath), "USER_AGENTS.md")
	body := mergeUserAgents(raw, userSrc)

	if stripHooks {
		body = stripHookableSections(body)
	} else {
		body = stripHookableDelimiterLines(body)
	}
	root := repoRoot()
	header := fmt.Sprintf(`---
description: Machine-wide context from %s/GLOBAL_AGENTS.md
alwaysApply: true
---

`, root)
	os.WriteFile(dest, []byte(header+body), 0644)
	fmt.Println(installSuccessStyle.Render(fmt.Sprintf("Wrote: %s", dest)))
}

func deployHookScripts(dryRun bool) string {
	srcDir := filepath.Join(repoRoot(), "hooks")
	destDir := filepath.Join(getHomeDir(), ".agents-hooks")
	scripts := []string{
		"rtk-prepend.sh",
		"claude-rtk.sh",
		"gemini-rtk.sh",
		"cursor-rtk.sh",
	}
	if dryRun {
		for _, s := range scripts {
			fmt.Println(installInfoStyle.Render(fmt.Sprintf("[dry-run] cp %s -> %s", filepath.Join(srcDir, s), filepath.Join(destDir, s))))
		}
		return destDir
	}
	os.MkdirAll(destDir, 0755)
	for _, s := range scripts {
		src := filepath.Join(srcDir, s)
		dst := filepath.Join(destDir, s)
		b, _ := os.ReadFile(src)
		os.WriteFile(dst, b, 0755)
	}
	fmt.Println(installSuccessStyle.Render(fmt.Sprintf("Deployed hook scripts to %s", destDir)))
	return destDir
}

func loadSnippet(name, hooksDir string) map[string]interface{} {
	raw, _ := os.ReadFile(filepath.Join(repoRoot(), "hooks", name))
	s := strings.ReplaceAll(string(raw), "<HOOKS_DIR>", hooksDir)
	var snippet map[string]interface{}
	json.Unmarshal([]byte(s), &snippet)
	return snippet
}

func mergeHooksIntoSettings(settingsPath string, snippet map[string]interface{}, hookKey, matchField string, dryRun bool) {
	if dryRun {
		fmt.Println(installInfoStyle.Render(fmt.Sprintf("[dry-run] merge hooks into %s (key: %s)", settingsPath, hookKey)))
		return
	}
	os.MkdirAll(filepath.Dir(settingsPath), 0755)
	existing := make(map[string]interface{})
	if b, err := os.ReadFile(settingsPath); err == nil {
		json.Unmarshal(b, &existing)
	}

	hooksSection, ok := existing["hooks"].(map[string]interface{})
	if !ok {
		hooksSection = make(map[string]interface{})
		existing["hooks"] = hooksSection
	}

	existingEntries, ok := hooksSection[hookKey].([]interface{})
	if !ok {
		existingEntries = []interface{}{}
	}

	snippetHooks, _ := snippet["hooks"].(map[string]interface{})
	newEntries, _ := snippetHooks[hookKey].([]interface{})

	for _, newEntryIface := range newEntries {
		newEntry := newEntryIface.(map[string]interface{})
		var newID string
		if hks, ok := newEntry["hooks"].([]interface{}); ok && len(hks) > 0 {
			if hm, ok := hks[0].(map[string]interface{}); ok {
				newID, _ = hm[matchField].(string)
			}
		} else {
			newID, _ = newEntry[matchField].(string)
		}

		replaced := false
		for i, oldEntryIface := range existingEntries {
			oldEntry, ok := oldEntryIface.(map[string]interface{})
			if !ok {
				continue
			}
			var oldID string
			if hks, ok := oldEntry["hooks"].([]interface{}); ok && len(hks) > 0 {
				if hm, ok := hks[0].(map[string]interface{}); ok {
					oldID, _ = hm[matchField].(string)
				}
			} else {
				oldID, _ = oldEntry[matchField].(string)
			}
			if oldID != "" && oldID == newID {
				existingEntries[i] = newEntry
				replaced = true
				break
			}
		}
		if !replaced {
			existingEntries = append(existingEntries, newEntry)
		}
	}

	hooksSection[hookKey] = existingEntries
	outBytes, _ := json.MarshalIndent(existing, "", "  ")
	os.WriteFile(settingsPath, append(outBytes, '\n'), 0644)
	fmt.Println(installSuccessStyle.Render(fmt.Sprintf("Merged hooks into %s", settingsPath)))
}

func installHooksClaude(hooksDir string, dryRun bool) {
	snippet := loadSnippet("claude-settings-snippet.json", hooksDir)
	mergeHooksIntoSettings(filepath.Join(getHomeDir(), ".claude/settings.json"), snippet, "PreToolUse", "command", dryRun)
}

func installHooksGemini(hooksDir string, dryRun bool) {
	snippet := loadSnippet("gemini-settings-snippet.json", hooksDir)
	mergeHooksIntoSettings(filepath.Join(getGeminiConfigDir(), "settings.json"), snippet, "BeforeTool", "command", dryRun)
}

func installHooksCursor(hooksDir string, dryRun bool) {
	snippet := loadSnippet("cursor-hooks-snippet.json", hooksDir)
	mergeHooksIntoSettings(filepath.Join(getHomeDir(), ".cursor/hooks.json"), snippet, "preToolUse", "command", dryRun)
}

func targetWanted(name string, targets []string) bool {
	if len(targets) == 0 {
		return true
	}
	for _, t := range targets {
		if t == name {
			return true
		}
	}
	return false
}

func forcingTargets(targets []string) bool {
	return len(targets) > 0
}

func iterRepoSkillDirs() []string {
	root := filepath.Join(repoRoot(), "skills")
	var out []string
	entries, _ := os.ReadDir(root)
	for _, entry := range entries {
		if entry.IsDir() && !strings.HasPrefix(entry.Name(), ".") {
			if _, err := os.Stat(filepath.Join(root, entry.Name(), "SKILL.md")); err == nil {
				out = append(out, filepath.Join(root, entry.Name()))
			}
		}
	}
	return out
}

func copySkillsToUserDir(destSkillsRoot string, dryRun bool) int {
	skills := iterRepoSkillDirs()
	if len(skills) == 0 {
		return 0
	}
	if dryRun {
		for _, sdir := range skills {
			fmt.Println(installInfoStyle.Render(fmt.Sprintf("[dry-run] copytree %s -> %s", sdir, filepath.Join(destSkillsRoot, filepath.Base(sdir)))))
		}
		return len(skills)
	}
	os.MkdirAll(destSkillsRoot, 0755)
	n := 0
	for _, sdir := range skills {
		dst := filepath.Join(destSkillsRoot, filepath.Base(sdir))
		os.RemoveAll(dst)
		// simple copytree implementation
		exec.Command("cp", "-r", sdir, dst).Run()
		n++
	}
	fmt.Println(installSuccessStyle.Render(fmt.Sprintf("Copied %d skill(s) to %s", n, destSkillsRoot)))
	return n
}

var installCmd = &cobra.Command{
	Use:   "install",
	Short: "Deploy GLOBAL_AGENTS.md, hooks, and skills to tool paths",
	Run: func(cmd *cobra.Command, args []string) {
		useCopy, _ := cmd.Flags().GetBool("copy")
		dryRun, _ := cmd.Flags().GetBool("dry-run")
		verbose, _ := cmd.Flags().GetBool("verbose")
		targetsStr, _ := cmd.Flags().GetString("targets")
		var targets []string
		if targetsStr != "" {
			for _, t := range strings.Split(targetsStr, ",") {
				if strings.TrimSpace(t) != "" {
					targets = append(targets, strings.ToLower(strings.TrimSpace(t)))
				}
			}
		}
		noHooks, _ := cmd.Flags().GetBool("no-hooks")
		noSkills, _ := cmd.Flags().GetBool("no-skills")

		withHooks := !noHooks
		withSkills := !noSkills
		src := filepath.Join(repoRoot(), "GLOBAL_AGENTS.md")
		if _, err := os.Stat(src); err != nil {
			fmt.Fprintf(os.Stderr, "Missing source file: %s\n", src)
			os.Exit(1)
		}

		hooksDir := filepath.Join(getHomeDir(), ".agents-hooks")
		if withHooks {
			hooksDir = deployHookScripts(dryRun)
		}

		installed := false
		didClaude, didGemini, didCursor, didAntigravity := false, false, false, false

		if targetWanted("claude", targets) {
			if detectClaude(verbose) || forcingTargets(targets) {
				if !detectClaude(verbose) && forcingTargets(targets) {
					fmt.Println(installWarnStyle.Render(fmt.Sprintf("Warning: claude-code not detected; writing %s anyway (--targets).", filepath.Join(getHomeDir(), ".claude/CLAUDE.md"))))
				}
				if withHooks {
					deployGlobalAgentsMarkdown(src, filepath.Join(getHomeDir(), ".claude/CLAUDE.md"), true, useCopy, dryRun)
					installHooksClaude(hooksDir, dryRun)
				} else {
					deployGlobalAgentsMarkdown(src, filepath.Join(getHomeDir(), ".claude/CLAUDE.md"), false, useCopy, dryRun)
				}
				installed = true
				didClaude = true
			}
		}

		geminiPathsRequested := targetWanted("gemini", targets) || targetWanted("antigravity", targets)
		geminiDetected := detectGemini(verbose)
		antigravityDetected := detectAntigravity(verbose)
		geminiStackDetected := geminiDetected || antigravityDetected

		if geminiPathsRequested {
			if geminiStackDetected || forcingTargets(targets) {
				if !geminiStackDetected && forcingTargets(targets) {
					fmt.Println(installWarnStyle.Render(fmt.Sprintf("Warning: gemini-cli / antigravity not detected; writing %s anyway (--targets).", filepath.Join(getGeminiConfigDir(), "GEMINI.md"))))
				}

				isAntigravityForced := forcingTargets(targets) && targetWanted("antigravity", targets)
				needsMarkdownHooks := antigravityDetected || isAntigravityForced
				stripMarkdown := withHooks && !needsMarkdownHooks

				deployGlobalAgentsMarkdown(src, filepath.Join(getGeminiConfigDir(), "GEMINI.md"), stripMarkdown, useCopy, dryRun)

				isGeminiForced := forcingTargets(targets) && targetWanted("gemini", targets)
				if withHooks && (geminiDetected || isGeminiForced) {
					installHooksGemini(hooksDir, dryRun)
				}

				if antigravityDetected || isAntigravityForced {
					didAntigravity = true
				}

				installed = true
				_ = didGemini
			}
		}

		if targetWanted("cursor", targets) {
			if detectCursor(verbose) || forcingTargets(targets) {
				if !detectCursor(verbose) && forcingTargets(targets) {
					fmt.Println(installWarnStyle.Render("Warning: cursor dirs not detected; writing ~/.cursor/rules/global-agents.mdc anyway (--targets)."))
				}
				writeCursorMdc(src, withHooks, dryRun)
				if withHooks {
					installHooksCursor(hooksDir, dryRun)
				}
				installed = true
				didCursor = true
			}
		}

		if withSkills {
			if repoSkillCount() == 0 {
				fmt.Fprintln(os.Stderr, installWarnStyle.Render("Note: skills deploy requested but no skill dirs with SKILL.md under skills/; skipping."))
			} else {
				if didClaude {
					copySkillsToUserDir(filepath.Join(getHomeDir(), ".claude/skills"), dryRun)
				}
				if didCursor {
					copySkillsToUserDir(filepath.Join(getHomeDir(), ".cursor/skills"), dryRun)
				}
				if didAntigravity {
					copySkillsToUserDir(filepath.Join(getHomeDir(), ".gemini/antigravity/skills"), dryRun)
				}
			}
		}

		if !installed {
			fmt.Println(installErrorStyle.Render("Nothing installed. Try: agents-cli discover"))
			fmt.Println(installErrorStyle.Render("Force paths with: agents-cli install --targets claude,gemini,antigravity,cursor"))
			os.Exit(1)
		}
		writeLocalMergedGlobal(src, dryRun)
	},
}

func init() {
	rootCmd.AddCommand(installCmd)
	installCmd.Flags().Bool("copy", false, "Copy instead of symlink")
	installCmd.Flags().Bool("dry-run", false, "Print actions only")
	installCmd.Flags().BoolP("verbose", "v", false, "Verbose output")
	installCmd.Flags().String("targets", "", "Comma-separated: claude, gemini, antigravity, cursor")
	installCmd.Flags().Bool("no-hooks", false, "Skip hook deploy and settings merge")
	installCmd.Flags().Bool("no-skills", false, "Do not copy repo skills/")
}
